In [5]:
import numpy as np
import scipy

A = np.array([[-7, -2, 5],
              [6, 32, 21],
              [5, 12, 100]])

print("matrix A \n", A)

print("\n a_1,3 of A = " + str(A[0, 2]))  # note that indexing starts from zero


matrix A 
 [[ -7  -2   5]
 [  6  32  21]
 [  5  12 100]]

 a_1,3 of A = 5


In [2]:
# find the transpose
B = A.T

# NOTE: or using scipy
# B = scipy.transpose(A)

print("the transpose of matrix A =\n", B)

the transpose of matrix A =
 [[ -7   6   5]
 [ -2  32  12]
 [  5  21 100]]


In [3]:
# identity matrix
id_matrix = np.identity(4)
print("identity matrix: \n", id_matrix)

# first standard unit vector
e1 = id_matrix[:, [0]]
# e2 = id_matrix[:, [1]]
print("\n first standard column vector \n", e1)


identity matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 first standard column vector 
 [[1.]
 [0.]
 [0.]
 [0.]]


In [4]:
# zero matrix
zero_matrix = np.zeros((3, 3))
print("zero matrix: \n", zero_matrix)


zero matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print("are the dimensions right?")
print(np.shape(A)[1] == np.shape(B)[0])

# then we can do multiplication
# C = scipy.matmul(A, B)
C = np.matmul(A, B)
print("\n the product of A and B is \n", C)

# to show difference
D = np.matmul(B, A)
print("\n the product of B and A is \n", D)

are the dimensions right?
True

 the product of A and B is 
 [[   78    -1   441]
 [   -1  1501  2514]
 [  441  2514 10169]]

 the product of B and A is 
 [[  110   266   591]
 [  266  1172  1862]
 [  591  1862 10466]]


In [20]:
# dot product vs '*' mulitplication
C = np.array([[4, 5], [6, 7]])
print("\n A = ", A)
print("\n C = ", C)
print("\n what is A*C? \n", A*C)


 A =  [[-7 -5]
 [-1 -8]]

 C =  [[4 5]
 [6 7]]

 what is A*C? 
 [[-28 -25]
 [ -6 -56]]


In [25]:
# inverse of matrix
print("\n A = ", A)
inv_A = scipy.linalg.inv(A)
print("\n A^-1 = ", inv_A)
# print("\n A muliplied by it's inverse = \n", scipy.dot(A, inv_A))
print("\n A muliplied by it's inverse = \n", np.dot(A, inv_A))



 A =  [[-7 -5]
 [-1 -8]]

 A^-1 =  [[-0.15686275  0.09803922]
 [ 0.01960784 -0.1372549 ]]

 A muliplied by it's inverse = 
 [[1. 0.]
 [0. 1.]]


In [16]:
from scipy import linalg

# solving linear equations
A = np.array([[-7, -5], [-1, -8]])  # matrix of coeffients
b = np.array([[1], [-1]])               # vector, 1D

# solve Ax = b
x = scipy.linalg.solve(A, b)

print("\n solution of Ax = b \n x = ", x)


 solution of Ax = b 
 x =  [[-0.25490196]
 [ 0.15686275]]
