In [8]:
import numpy as np
import scipy

A = np.array([[-7, -2, 5], 
              [6, 32, 21],
              [5, 12, 100]])

print("matrix A \n", A)

print("\n a_1,3 of A = " + str(A[0][2])) # note that indexing starts from zero

matrix A 
 [[ -7  -2   5]
 [  6  32  21]
 [  5  12 100]]

 a_1,3 of A = 5


In [12]:
# find the transpose
B = A.T

# NOTE: or using scipy
# B = scipy.transpose(A)

print("the transpose of matrix A =\n", B)

the transpose of matrix A =
 [[ -7   6   5]
 [ -2  32  12]
 [  5  21 100]]


In [25]:
# identity matrix
id_matrix = np.identity(4)
print("identity matrix: \n", id_matrix)

# first standard unit vector
e1 = id_matrix[:, [0]]
# e2 = id_matrix[:, [1]]
print("\n first standard column vector \n", e1)


identity matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 first standard column vector 
 [[0.]
 [1.]
 [0.]
 [0.]]


In [17]:
# zero matrix
zero_matrix = np.zeros((3, 3))
print("zero matrix: \n", zero_matrix)


zero matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
