In [1]:
#  code for using scipy.linalg.lu to solve A x = b
#    uses scipy.linalg.lu to find A = Pt L U,
#    then uses scipy.linalg.solve_triangular to solve the resulting triangular systems

import scipy
import scipy.linalg
import numpy as np

A = np.array([[0.2, 1.4, -0.4, 12.3], [-2.3, 4.2, 1.1, -0.9],
             [9.2, -2.3, -0.1, 2.2], [3.4, 3.3, -10.1, 4.0]])
b = np.array([[0.2], [-1.2], [3.3], [0.2]])
#  linalg finds Pt, L and U such that A = Pt L U
#  (Pt is inverse of what we did in class; but for
#    permutation matrices, inverse of P is transpose of P)
Pt, L, U = scipy.linalg.lu(A)
P = Pt.T
Pb = scipy.matmul(P, b)
y = scipy.linalg.solve_triangular(L, Pb, lower=True)
x = scipy.linalg.solve_triangular(U, y, lower=False)

print('Matrix is\n')
print(A)
print('\n')

print('L=')
print(L)
print('\n')

print('U=')
print(U)
print('\n')

print('P=')
print(Pt.T)
print('\n')

print('Residual vector is\n')
print(scipy.matmul(A, x)-b)
print('\n')

#  Pt L U = A
#print(Pt @ L @ U-A)

#  P A = L U
#print(P @ A - L @ U)


Matrix is

[[  0.2   1.4  -0.4  12.3]
 [ -2.3   4.2   1.1  -0.9]
 [  9.2  -2.3  -0.1   2.2]
 [  3.4   3.3 -10.1   4. ]]


L=
[[ 1.          0.          0.          0.        ]
 [ 0.36956522  1.          0.          0.        ]
 [-0.25        0.87349398  1.          0.        ]
 [ 0.02173913  0.34939759  0.3160846   1.        ]]


U=
[[  9.2         -2.3         -0.1          2.2       ]
 [  0.           4.15       -10.06304348   3.18695652]
 [  0.           0.           9.86500786  -3.13378732]
 [  0.           0.           0.          12.12920089]]


P=
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


Residual vector is

[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-5.55111512e-17]]




<ipython-input-1-4523d2ae6d62>:17: DeprecationWarning: scipy.matmul is deprecated and will be removed in SciPy 2.0.0, use numpy.matmul instead
  Pb = scipy.matmul(P, b)
<ipython-input-1-4523d2ae6d62>:38: DeprecationWarning: scipy.matmul is deprecated and will be removed in SciPy 2.0.0, use numpy.matmul instead
  print(scipy.matmul(A, x)-b)
