In [1]:
# LU decomposition without pivoting (not for practical use)

import numpy as np

def LU(A):
    N = np.shape(A)[0]  # get row/col dimension of A 

    # initialize matrices
    U = np.copy(A)      # use np.copy() not assignment (to avoid using pointers and modifies the original array)
    L = np.identity(N)  # identity matrix of size A

    for j in range(N - 1):             # looping over columns (pivots); excluding the last row
        for i in range(j + 1, N):      # start from the entry below the pivot
            L[i, j] = U[i, j] / U[j, j]

            U[i, :] = U[i, :] - L[i, j] * U[j, :]

    return L, U

In [6]:
A = np.array([[2, 1, 1, 0], [4, 3, 3, 1], [8, 7, 9, 5], [6, 7, 9, 8]])

L, U = LU(A)

print("L: \n", L)
print("\nU: \n", U)

print("is A = LU? \n")
print("LU: \n", np.dot(L, U))

print("\nA: \n", A)

L: 
 [[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [4. 3. 1. 0.]
 [3. 4. 1. 1.]]

U: 
 [[2 1 1 0]
 [0 1 1 1]
 [0 0 2 2]
 [0 0 0 2]]
is A = LU? 

LU: 
 [[2. 1. 1. 0.]
 [4. 3. 3. 1.]
 [8. 7. 9. 5.]
 [6. 7. 9. 8.]]

A: 
 [[2 1 1 0]
 [4 3 3 1]
 [8 7 9 5]
 [6 7 9 8]]


In [10]:
# what happens if you change an entry (pivot) to zero?
A = np.array([[4, 1, 1, 0], [4, 3, 3, 1], [8, 5, 5, 1], [6, 7, 9, 8]])

L, U = LU(A)

print("L: \n", L)
print("\nU: \n", U)

print("is A = LU? \n")
print("LU: \n", np.dot(L, U))

print("\nA: \n", A)

L: 
 [[1.  0.  0.  0. ]
 [1.  1.  0.  0. ]
 [2.  1.5 1.  0. ]
 [1.5 2.5 inf 1. ]]

U: 
 [[          4           1           1           0]
 [          0           2           2           1]
 [          0           0           0           0]
 [-2147483648 -2147483648 -2147483648 -2147483648]]
is A = LU? 

LU: 
 [[4.  1.  1.  0. ]
 [4.  3.  3.  1. ]
 [8.  5.  5.  1.5]
 [nan nan nan nan]]

A: 
 [[4 1 1 0]
 [4 3 3 1]
 [8 5 5 1]
 [6 7 9 8]]


<ipython-input-1-6b9b2c52a72f>:14: RuntimeWarning: divide by zero encountered in long_scalars
  L[i, j] = U[i, j] / U[j, j]
<ipython-input-1-6b9b2c52a72f>:16: RuntimeWarning: invalid value encountered in multiply
  U[i, :] = U[i, :] - L[i, j] * U[j, :]
